[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/KillTheMule/nvim-rs?rev=764dd270c642f77f10f3e19d05cc178a6cbe69f3"]
git = "https://github.com/KillTheMule/nvim-rs"
rev = "764dd270c642f77f10f3e19d05cc178a6cbe69f3"
replace-with = "vendored-sources"

[source."git+https://github.com/RustAudio/rodio?rev=e2074c6c2acf07b57cf717e076bdda7a9ac6e70b"]
git = "https://github.com/RustAudio/rodio"
rev = "e2074c6c2acf07b57cf717e076bdda7a9ac6e70b"
replace-with = "vendored-sources"

[source."git+https://github.com/camdencheek/tree-sitter-go-mod?rev=2e886870578eeba1927a2dc4bd2e2b3f598c5f9a"]
git = "https://github.com/camdencheek/tree-sitter-go-mod"
rev = "2e886870578eeba1927a2dc4bd2e2b3f598c5f9a"
replace-with = "vendored-sources"

[source."git+https://github.com/kvark/blade?rev=e3cf011ca18a6dfd907d1dedd93e85e21f005fe3"]
git = "https://github.com/kvark/blade"
rev = "e3cf011ca18a6dfd907d1dedd93e85e21f005fe3"
replace-with = "vendored-sources"

[source."git+https://github.com/microsoft/python-environment-tools.git?rev=d5b5bb0c4558a51d8cc76b514bc870fd1c042f16"]
git = "https://github.com/microsoft/python-environment-tools.git"
rev = "d5b5bb0c4558a51d8cc76b514bc870fd1c042f16"
replace-with = "vendored-sources"

[source."git+https://github.com/smol-rs/async-task.git?rev=b4486cd71e4e94fbda54ce6302444de14f4d190e"]
git = "https://github.com/smol-rs/async-task.git"
rev = "b4486cd71e4e94fbda54ce6302444de14f4d190e"
replace-with = "vendored-sources"

[source."git+https://github.com/tree-sitter-grammars/tree-sitter-markdown?rev=9a23c1a96c0513d8fc6520972beedd419a973539"]
git = "https://github.com/tree-sitter-grammars/tree-sitter-markdown"
rev = "9a23c1a96c0513d8fc6520972beedd419a973539"
replace-with = "vendored-sources"

[source."git+https://github.com/tree-sitter/tree-sitter-cpp?rev=5cb9b693cfd7bfacab1d9ff4acac1a4150700609"]
git = "https://github.com/tree-sitter/tree-sitter-cpp"
rev = "5cb9b693cfd7bfacab1d9ff4acac1a4150700609"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/alacritty?rev=936aee8761a17affc84ab418ae21306c27c26221"]
git = "https://github.com/zed-industries/alacritty"
rev = "936aee8761a17affc84ab418ae21306c27c26221"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/async-pipe-rs?rev=82d00a04211cf4e1236029aa03e6b6ce2a74c553"]
git = "https://github.com/zed-industries/async-pipe-rs"
rev = "82d00a04211cf4e1236029aa03e6b6ce2a74c553"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/calloop"]
git = "https://github.com/zed-industries/calloop"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/candle?branch=9.1-patched"]
git = "https://github.com/zed-industries/candle"
branch = "9.1-patched"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/dap-types?rev=1b461b310481d01e02b2603c16d7144b926339f8"]
git = "https://github.com/zed-industries/dap-types"
rev = "1b461b310481d01e02b2603c16d7144b926339f8"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/font-kit?rev=110523127440aefb11ce0cf280ae7c5071337ec5"]
git = "https://github.com/zed-industries/font-kit"
rev = "110523127440aefb11ce0cf280ae7c5071337ec5"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/gh-workflow?rev=c9eac0ed361583e1072860d96776fa52775b82ac"]
git = "https://github.com/zed-industries/gh-workflow"
rev = "c9eac0ed361583e1072860d96776fa52775b82ac"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/livekit-rust-sdks?rev=5f04705ac3f356350ae31534ffbc476abc9ea83d"]
git = "https://github.com/zed-industries/livekit-rust-sdks"
rev = "5f04705ac3f356350ae31534ffbc476abc9ea83d"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/lsp-types?rev=b71ab4eeb27d9758be8092020a46fe33fbca4e33"]
git = "https://github.com/zed-industries/lsp-types"
rev = "b71ab4eeb27d9758be8092020a46fe33fbca4e33"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/notify.git?rev=6c550ac3c56cbd143c57ea6390e197af9d790908"]
git = "https://github.com/zed-industries/notify.git"
rev = "6c550ac3c56cbd143c57ea6390e197af9d790908"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/reqwest.git?rev=c15662463bda39148ba154100dd44d3fba5873a4"]
git = "https://github.com/zed-industries/reqwest.git"
rev = "c15662463bda39148ba154100dd44d3fba5873a4"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/scap?rev=4afea48c3b002197176fb19cd0f9b180dd36eaac"]
git = "https://github.com/zed-industries/scap"
rev = "4afea48c3b002197176fb19cd0f9b180dd36eaac"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/tiktoken-rs?rev=2570c4387a8505fb8f1d3f3557454b474f1e8271"]
git = "https://github.com/zed-industries/tiktoken-rs"
rev = "2570c4387a8505fb8f1d3f3557454b474f1e8271"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/tree-sitter-git-commit?rev=88309716a69dd13ab83443721ba6e0b491d37ee9"]
git = "https://github.com/zed-industries/tree-sitter-git-commit"
rev = "88309716a69dd13ab83443721ba6e0b491d37ee9"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/tree-sitter-go-work?rev=acb0617bf7f4fda02c6217676cc64acb89536dc7"]
git = "https://github.com/zed-industries/tree-sitter-go-work"
rev = "acb0617bf7f4fda02c6217676cc64acb89536dc7"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/tree-sitter-heex?rev=1dd45142fbb05562e35b2040c6129c9bca346592"]
git = "https://github.com/zed-industries/tree-sitter-heex"
rev = "1dd45142fbb05562e35b2040c6129c9bca346592"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/tree-sitter-typescript?rev=e2c53597d6a5d9cf7bbe8dccde576fe1e46c5899"]
git = "https://github.com/zed-industries/tree-sitter-typescript"
rev = "e2c53597d6a5d9cf7bbe8dccde576fe1e46c5899"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/tree-sitter-yaml?rev=baff0b51c64ef6a1fb1f8390f3ad6015b83ec13a"]
git = "https://github.com/zed-industries/tree-sitter-yaml"
rev = "baff0b51c64ef6a1fb1f8390f3ad6015b83ec13a"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/windows-capture.git?rev=f0d6c1b6691db75461b732f6d5ff56eed002eeb9"]
git = "https://github.com/zed-industries/windows-capture.git"
rev = "f0d6c1b6691db75461b732f6d5ff56eed002eeb9"
replace-with = "vendored-sources"

[source."git+https://github.com/zed-industries/xim-rs.git?rev=16f35a2c881b815a2b6cdfd6687988e84f8447d8"]
git = "https://github.com/zed-industries/xim-rs.git"
rev = "16f35a2c881b815a2b6cdfd6687988e84f8447d8"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
